AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RorUrl

Parameters:

  RailsEnv:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production

Globals:

  Function:
    Environment:
      Variables:
        RAILS_ENV: !Ref RailsEnv
        TABLE_NAME: !Ref DynamoDBTable

Resources:

  RailsLambda:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: ./.lamby/RailsLambda
      Dockerfile: Dockerfile
      DockerTag: web
    Properties:
      Events:
        HttpApiProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref RailsHttpApi
      MemorySize: 1792
      PackageType: Image
      Timeout: 60
      Policies:
      # Give DynamoDB Full Access to your Lambda Function
      - AmazonDynamoDBFullAccess

  RailsHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref RailsEnv

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema: 
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  # https://docs.aws.amazon.com/lambda/latest/dg/kinesis-tutorial-spec.html
  # ProcessDynamoDBStream:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: handler
  #     Runtime: runtime
  #     Policies: AWSLambdaDynamoDBExecutionRole
  #     Events:
  #       Stream:
  #         Type: DynamoDB
  #         Properties:
  #           Stream: !GetAtt DynamoDBTable.StreamArn
  #           BatchSize: 100
  #           StartingPosition: TRIM_HORIZON


Outputs:

  RorUrlHttpApiUrl:
    Description: Lambda Invoke URL
    Value: !Sub https://${RailsHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${RailsEnv}/

  RorUrlLambdaResourceArn:
    Description: Lambda ARN
    Value: RailsLambda.Arn
